# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.



# Site settings
title: Tyler Lee
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here.  It will appear in your document head meta (for
  Google search results)

baseurl: "" # if you want to have a different base url for site
url: "http://tylerjlee.me" # specify protocol as well



# User Info
twitter_username: tlee753
github_username:  tlee753
email: tlee753@gatech.edu



# Build settings
markdown: kramdown
