# Site settings
title: Tyler Lee
tagline: Leader // Explorer // Engineer
description: >
  I am an avid code junkie, space afficianado, and helluva engineer - brace yourself for my upcoming awesome website

baseurl: ""
url: "http://tylerjlee.me" # specify protocol as well


# User Info
twitter_username: tlee753
github_username:  tlee753
email: tlee753@gatech.edu


# Build settings
markdown: kramdown
port: 8000


sass:
  sass_dir: css
  style: :nested